version: '1.0'
name: paper-inhatc

secrets:
  main_db-password:
    file: mysql/password.txt

volumes:
  main-mysql_db-data: { }

networks:
  front-tier:
    external: true

  back-main-tier:
    external: true

services:
  reverse_proxy:
    image: nginx:latest
    ports: # https://docs.docker.com/compose/compose-file/05-services/#long-syntax-3
      - "80:80"
    depends_on:
      cache_server:
        condition: service_started
      main_server:
        condition: service_started
      auth_server:
        condition: service_started
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  main_server:
    hostname: mainHost
    build: ./main
    ports:
      - "8080:8080"
    restart: no
    depends_on:
      main_db:
        condition: service_healthy
  main_db:
    hostname: mysqlHost_main
    image: mysql:8
    expose:
      - 3306
      - 33060
    restart: no
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysqlHost_main", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_DATABASE=coupang
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/main_db-password
    secrets:
      - main_db-password
    volumes:
      - main-mysql_db-data:/var/lib/mysql
  auth_server:
    hostname: authHost
    build: ./auth
    ports:
      - "9000:9000"
    restart: no
    depends_on:
      cache_redis_db:
        condition: service_healthy
      cache_mysql_db:
        condition: service_healthy




